// ===== VERİ KALİTESİ KONTROL MERKEZİ =====
import { getCurrentUser } from '../state.js';
import { showToast } from '../notifications.js';
import { canManage } from '../services/enterprise-storage.js';
import { runDataQualityScan, readDataQualitySnapshot, updateDataQualityFinding, exportDataQualityEvidence } from '../services/data-quality.js';

const t = (key, values) => window.miniappI18n?.t(key, values) ?? key;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const date = value => value ? new Date(value).toLocaleString('tr-TR') : '—';
const actor = () => getCurrentUser()?.username || 'system';

export async function renderDataQualityPage(container) {
  container.innerHTML = `<div class="card loading-pulse text-slate-400">${t('data_quality.loading')}</div>`;
  try {
    let snapshot = await readDataQualitySnapshot();
    const writable = getCurrentUser()?.role === 'admin' && canManage();
    const render = (notice = '') => {
      const counts = snapshot?.counts || { records: 0, users: 0, schedules: 0, findings: 0, critical: 0, high: 0, medium: 0, open: 0 };
      const findings = snapshot?.findings || [];
      const rows = findings.map(item => `<article class="dq-finding severity-${esc(item.severity)} status-${esc(item.status)}" data-category="${esc(item.category)}" data-status="${esc(item.status)}"><div class="dq-finding-head"><div><span class="dq-category">${t(`data_quality.category_${item.category}`)}</span><h3>${esc(item.title)}</h3></div><div class="dq-badges"><span class="dq-badge severity-${esc(item.severity)}">${t(`data_quality.severity_${item.severity}`)}</span><span class="dq-badge status-${esc(item.status)}">${t(`data_quality.status_${item.status}`)}</span></div></div><p>${esc(item.detail)}</p><div class="dq-meta"><span>${t('data_quality.recommendation')}: <strong>${esc(item.recommendation)}</strong></span><span>${t('data_quality.occurrences')}: <strong>${Number(item.occurrences || 1)}</strong></span></div><div class="dq-actions">${writable ? `<button class="btn-secondary" data-dq-action="acknowledged" data-id="${esc(item.id)}">${t('data_quality.acknowledge')}</button><button class="btn-primary" data-dq-action="resolved" data-id="${esc(item.id)}">${t('data_quality.resolve')}</button><button class="btn-secondary" data-dq-action="open" data-id="${esc(item.id)}">${t('data_quality.reopen')}</button>` : `<span>${t('data_quality.read_only')}</span>`}</div></article>`).join('');
      container.innerHTML = `<div class="dq-page fade-in"><header class="dq-hero"><div><p class="dq-kicker">${t('data_quality.eyebrow')}</p><h1>${t('data_quality.title')}</h1><p>${t('data_quality.subtitle')}</p></div><div class="dq-scan-state"><strong>${snapshot ? t('data_quality.scan_ready') : t('data_quality.scan_needed')}</strong><span>${snapshot ? `${t('data_quality.last_scan')}: ${date(snapshot.scannedAt)}` : t('data_quality.no_scan')}</span></div></header><div class="dq-boundary"><strong>${t('data_quality.boundary_title')}</strong><span>${t('data_quality.boundary_text')}</span></div><section class="dq-kpis"><div class="dq-kpi info"><span>${t('data_quality.kpi_records')}</span><strong>${counts.records}</strong><small>${counts.users} ${t('data_quality.users')} · ${counts.schedules} ${t('data_quality.schedules')}</small></div><div class="dq-kpi danger"><span>${t('data_quality.kpi_critical')}</span><strong>${counts.critical}</strong><small>${t('data_quality.kpi_critical_note')}</small></div><div class="dq-kpi warning"><span>${t('data_quality.kpi_high')}</span><strong>${counts.high}</strong><small>${t('data_quality.kpi_high_note')}</small></div><div class="dq-kpi success"><span>${t('data_quality.kpi_open')}</span><strong>${counts.open}</strong><small>${t('data_quality.kpi_open_note')}</small></div></section><p class="dq-notice">${esc(notice)}</p><section class="card dq-workspace"><div class="dq-toolbar"><div><h2>${t('data_quality.queue_title')}</h2><p>${t('data_quality.queue_note')}</p></div><div class="dq-toolbar-actions"><select id="dq-category" class="input-field" aria-label="${t('data_quality.filter_label')}"><option value="all">${t('data_quality.filter_all')}</option><option value="duplicate">${t('data_quality.category_duplicate')}</option><option value="missing">${t('data_quality.category_missing')}</option><option value="invalid">${t('data_quality.category_invalid')}</option><option value="inconsistent">${t('data_quality.category_inconsistent')}</option></select><select id="dq-status" class="input-field" aria-label="${t('data_quality.status_filter_label')}"><option value="all">${t('data_quality.filter_all_status')}</option><option value="open">${t('data_quality.status_open')}</option><option value="acknowledged">${t('data_quality.status_acknowledged')}</option><option value="resolved">${t('data_quality.status_resolved')}</option></select><button id="dq-scan" class="btn-primary">${t('data_quality.run_scan')}</button><button id="dq-export" class="btn-secondary" ${snapshot ? '' : 'disabled'}>${t('data_quality.export')}</button></div></div><div id="dq-list" class="dq-list">${rows || `<div class="dq-empty"><strong>${t('data_quality.empty_title')}</strong><p>${t('data_quality.empty_note')}</p></div>`}</div></section></div>`;
      bind();
    };
    const bind = () => {
      const apply = () => { const category = container.querySelector('#dq-category')?.value || 'all'; const status = container.querySelector('#dq-status')?.value || 'all'; container.querySelectorAll('.dq-finding').forEach(row => { row.hidden = (category !== 'all' && row.dataset.category !== category) || (status !== 'all' && row.dataset.status !== status); }); };
      container.querySelector('#dq-category')?.addEventListener('change', apply); container.querySelector('#dq-status')?.addEventListener('change', apply);
      container.querySelector('#dq-scan')?.addEventListener('click', async event => { event.currentTarget.disabled = true; try { snapshot = await runDataQualityScan(actor()); render(t('data_quality.scan_complete')); } catch { showToast(t('data_quality.error'), 'error'); event.currentTarget.disabled = false; } });
      container.querySelector('#dq-export')?.addEventListener('click', async () => { try { await exportDataQualityEvidence(snapshot, actor()); showToast(t('data_quality.exported'), 'success'); } catch { showToast(t('data_quality.error'), 'error'); } });
      container.querySelectorAll('[data-dq-action]').forEach(button => button.addEventListener('click', async () => { button.disabled = true; try { snapshot = await updateDataQualityFinding(button.dataset.id, button.dataset.dqAction, actor()); render(t('data_quality.status_saved')); } catch { button.disabled = false; showToast(t('data_quality.error'), 'error'); } }));
    };
    render();
  } catch (error) { container.innerHTML = `<div class="card border-red-400/20"><h1 class="text-xl font-bold text-white">${t('data_quality.load_error')}</h1><p class="text-slate-400 mt-2">${t('data_quality.error')}</p></div>`; console.error('[Hastane PYS] Veri kalitesi merkezi yüklenemedi', error); }
}
