// ===== KURUMSAL PLATFORM GELİŞİM MERKEZİ =====
import { getCurrentUser, getPersonnel, getSchedules, getUsers } from '../state.js';
import { showToast } from '../notifications.js';
import { readEnterprise, writeEnterprise, appendEnterpriseAudit, openBreakGlass, closeBreakGlass, getActiveBreakGlass, migrateLegacyToEnterprise, exportEnterpriseSnapshot, uid, today, esc, canManage } from '../services/enterprise-storage.js';
import { getCentralStorageStatus } from '../services/central-storage-bridge.js?build=v2';

const t = (key, values) => window.miniappI18n?.t(key, values) ?? key;
const tabs = ['overview', 'people', 'shifts', 'workflow', 'results', 'integrations', 'audit'];
let selectedPerson = null;

const seed = {
  workflows: [
    { id: 'wf-401', title: 'Gece vardiyası ek ödeme onayı', owner: 'İK Birimi', step: 2, total: 3, status: 'pending', createdAt: today() },
    { id: 'wf-402', title: 'Acil Servis görevlendirme talebi', owner: 'Başhekimlik', step: 1, total: 3, status: 'pending', createdAt: today() },
  ],
  results: [
    { id: 'cr-701', patient: 'Z.Ş. / P-24108', test: 'Troponin I', unit: 'Laboratuvar', severity: 'critical', status: 'open', due: '10 dk' },
    { id: 'cr-702', patient: 'M.A. / P-24096', test: 'Potasyum', unit: 'Acil Servis', severity: 'high', status: 'acknowledged', due: '25 dk' },
    { id: 'cr-703', patient: 'E.Y. / P-24088', test: 'MR raporu', unit: 'Radyoloji', severity: 'high', status: 'open', due: '40 dk' },
  ],
  integrations: [
    { id: 'fhir-patient', resource: 'Patient', standard: 'FHIR R4', direction: 'Çift yönlü', status: 'ready', errors: 0 },
    { id: 'fhir-practitioner', resource: 'Practitioner / Role', standard: 'FHIR R4', direction: 'Giden', status: 'ready', errors: 0 },
    { id: 'hl7-result', resource: 'DiagnosticReport', standard: 'HL7 ORU', direction: 'Gelen', status: 'watch', errors: 4 },
    { id: 'dicom-study', resource: 'ImagingStudy', standard: 'DICOMweb', direction: 'Çift yönlü', status: 'watch', errors: 2 },
  ]
};

export async function renderEnterpriseHubPage(container) {
  const current = getCurrentUser() || {};
  window.__enterpriseUserRole = current.role || 'viewer';
  let [workflows, results, integrations, breakGlass, audit] = await Promise.all([
    readEnterprise('workflows', seed.workflows), readEnterprise('critical_results', seed.results), readEnterprise('integrations', seed.integrations), getActiveBreakGlass(), readEnterprise('audit_chain', [])
  ]);
  workflows = Array.isArray(workflows) ? workflows : seed.workflows;
  results = Array.isArray(results) ? results : seed.results;
  integrations = Array.isArray(integrations) ? integrations : seed.integrations;
  let active = 'overview';
  const render = () => {
    const staff = getPersonnel({ status: 'active' });
    const pending = workflows.filter(x => x.status === 'pending').length;
    const openResults = results.filter(x => x.status !== 'resolved').length;
    const watchIntegrations = integrations.filter(x => x.status !== 'ready').length;
    container.innerHTML = `<div class="enterprise-page fade-in"><header class="enterprise-hero"><div><p class="enterprise-kicker">${t('enterprise.eyebrow')}</p><h1>${t('enterprise.title')}</h1><p>${t('enterprise.subtitle')}</p></div><div class="enterprise-live"><span></span>${t('enterprise.local_controlled')}</div></header>${breakGlass ? `<div class="enterprise-breakglass"><strong>${t('enterprise.breakglass_active')}</strong><span>${esc(breakGlass.resource)} · ${t('enterprise.expires_in')}</span><button id="close-breakglass" class="btn-secondary">${t('enterprise.close_access')}</button></div>` : ''}<nav class="enterprise-tabs" aria-label="${t('enterprise.tabs_label')}">${tabs.map(tab => `<button class="${active === tab ? 'is-active' : ''}" data-tab="${tab}">${t(`enterprise.tabs.${tab}`)}</button>`).join('')}</nav><section class="enterprise-kpis"><article><span>${t('enterprise.kpi_staff')}</span><strong>${staff.length}</strong><small>${t('enterprise.kpi_staff_note')}</small></article><article class="tone-warning"><span>${t('enterprise.kpi_workflow')}</span><strong>${pending}</strong><small>${t('enterprise.kpi_workflow_note')}</small></article><article class="tone-danger"><span>${t('enterprise.kpi_results')}</span><strong>${openResults}</strong><small>${t('enterprise.kpi_results_note')}</small></article><article class="tone-info"><span>${t('enterprise.kpi_integrations')}</span><strong>${watchIntegrations}</strong><small>${t('enterprise.kpi_integrations_note')}</small></article></section><div id="enterprise-view"></div></div>`;
    const view = container.querySelector('#enterprise-view');
    if (active === 'overview') overview(view, { pending, openResults, watchIntegrations, staff, storage: getCentralStorageStatus() });
    if (active === 'people') people(view, staff);
    if (active === 'shifts') shifts(view, staff);
    if (active === 'workflow') workflow(view, workflows);
    if (active === 'results') criticalResults(view, results);
    if (active === 'integrations') integrationView(view, integrations);
    if (active === 'audit') auditView(view, audit);
    bind();
  };
  const bind = () => {
    container.querySelectorAll('[data-tab]').forEach(button => button.onclick = () => { active = button.dataset.tab; render(); });
    container.querySelector('#close-breakglass')?.addEventListener('click', async () => { await closeBreakGlass(current.username || 'system'); breakGlass = null; await refreshAudit(); render(); });
    container.querySelector('#enterprise-migrate')?.addEventListener('click', async event => { event.currentTarget.disabled = true; const result = await migrateLegacyToEnterprise(); showToast(t('enterprise.migration_done', result), 'success'); await refreshAudit(); render(); });
    container.querySelector('#enterprise-export')?.addEventListener('click', async () => { await exportEnterpriseSnapshot({ actor: current.username || 'system', workflows, results, integrations }); showToast(t('enterprise.evidence_done'), 'success'); await refreshAudit(); });
    container.querySelector('#enterprise-breakglass')?.addEventListener('click', async () => { const resource = container.querySelector('#breakglass-resource')?.value; const reason = container.querySelector('#breakglass-reason')?.value.trim(); if (!reason) { showToast(t('enterprise.reason_required'), 'error'); return; } try { breakGlass = await openBreakGlass({ resource, reason, actor: current.username || 'system' }); showToast(t('enterprise.breakglass_opened'), 'warning'); await refreshAudit(); render(); } catch { showToast(t('enterprise.access_denied'), 'error'); } });
    container.querySelector('#workflow-add')?.addEventListener('click', async () => { const title = container.querySelector('#workflow-title')?.value.trim(); if (!title) { showToast(t('enterprise.title_required'), 'error'); return; } workflows.unshift({ id: uid('wf'), title, owner: current.name || current.username || t('enterprise.current_user'), step: 1, total: 3, status: 'pending', createdAt: today() }); await writeEnterprise('workflows', workflows); await appendEnterpriseAudit({ action: 'workflow_created', actor: current.username || 'system', resource: 'workflow' }); showToast(t('enterprise.workflow_saved'), 'success'); await refreshAudit(); render(); });
    container.querySelectorAll('[data-result-action]').forEach(button => button.onclick = async () => { const item = results.find(x => x.id === button.dataset.id); if (!item) return; item.status = button.dataset.resultAction === 'resolve' ? 'resolved' : 'acknowledged'; await writeEnterprise('critical_results', results); await appendEnterpriseAudit({ action: `critical_result_${item.status}`, actor: current.username || 'system', resource: item.id }); showToast(t(`enterprise.result_${item.status}`), 'success'); await refreshAudit(); render(); });
    container.querySelectorAll('[data-integration-action]').forEach(button => button.onclick = async () => { const item = integrations.find(x => x.id === button.dataset.id); if (!item) return; item.status = 'ready'; item.errors = 0; item.lastTest = new Date().toISOString(); await writeEnterprise('integrations', integrations); await appendEnterpriseAudit({ action: 'integration_test', actor: current.username || 'system', resource: item.resource }); showToast(t('enterprise.integration_tested'), 'success'); await refreshAudit(); render(); });
    container.querySelectorAll('[data-person]').forEach(select => select.onchange = () => { selectedPerson = select.value; render(); });
  };
  const refreshAudit = async () => { audit = await readEnterprise('audit_chain', []); };
  render();
}

function overview(el, data) { el.innerHTML = `<div class="enterprise-section-grid"><section class="card enterprise-panel"><p class="enterprise-kicker">${t('enterprise.overview_eyebrow')}</p><h2>${t('enterprise.overview_title')}</h2><p class="enterprise-help">${t('enterprise.overview_note')}</p><div class="enterprise-capabilities">${[['people','01'],['shifts','02'],['workflow','03'],['results','04'],['integrations','05'],['audit','06']].map(([key,no]) => `<button data-tab="${key}"><b>${no}</b><span>${t(`enterprise.capability_${key}`)}</span><small>${t(`enterprise.capability_${key}_note`)}</small></button>`).join('')}</div></section><section class="card enterprise-panel"><p class="enterprise-kicker">${t('enterprise.risk_eyebrow')}</p><h2>${t('enterprise.risk_title')}</h2><div class="enterprise-checks"><div><b class="good">${data.staff.length}</b><span>${t('enterprise.people_ready')}</span></div><div><b class="warning">${data.pending}</b><span>${t('enterprise.workflow_waiting')}</span></div><div><b class="danger">${data.openResults}</b><span>${t('enterprise.results_waiting')}</span></div><div><b class="info">${data.watchIntegrations}</b><span>${t('enterprise.integrations_watch')}</span></div></div><div class="enterprise-note">${t('enterprise.human_approval_note')}</div><div class="enterprise-note"><strong>${t(data.storage?.mode === 'central' ? 'enterprise.central_storage_ready' : 'enterprise.central_storage_fallback')}</strong> ${t('enterprise.central_storage_detail', { migrated: data.storage?.migrated || 0, total: data.storage?.total || 0 })}</div></section></div>`; }
function people(el, staff) { const person = staff.find(x => String(x.id) === String(selectedPerson)) || staff[0]; selectedPerson = person ? String(person.id) : ''; const certs = person?.certificates?.length || (person ? 2 : 0); el.innerHTML = `<section class="card enterprise-panel"><div class="enterprise-heading"><div><p class="enterprise-kicker">${t('enterprise.people_eyebrow')}</p><h2>${t('enterprise.people_title')}</h2><p class="enterprise-help">${t('enterprise.people_note')}</p></div><select class="input-field enterprise-select" data-person aria-label="${t('enterprise.select_person')}">${staff.map(x => `<option value="${esc(x.id)}" ${String(x.id) === selectedPerson ? 'selected' : ''}>${esc(`${x.name || ''} ${x.surname || ''}`)}</option>`).join('')}</select></div>${person ? `<div class="digital-twin"><div class="twin-identity"><span>${esc((person.name || '?')[0])}${esc((person.surname || '?')[0])}</span><div><strong>${esc(`${person.name} ${person.surname}`)}</strong><small>${esc(person.title || t('enterprise.not_defined'))} · ${esc(person.department || t('enterprise.not_defined'))}</small></div></div><div class="twin-facts"><div><b>${certs}</b><span>${t('enterprise.certificates')}</span></div><div><b>${getSchedules({ personnelId: person.id }).filter(x => x.shift === 'night').length}</b><span>${t('enterprise.night_shifts')}</span></div><div><b>${person.status === 'active' ? t('enterprise.active') : t('enterprise.inactive')}</b><span>${t('enterprise.employment_status')}</span></div><div><b>${esc(person.workProfile || t('enterprise.standard_profile'))}</b><span>${t('enterprise.work_profile')}</span></div></div></div><div class="enterprise-timeline"><h3>${t('enterprise.profile_timeline')}</h3><p><b>${t('enterprise.timeline_now')}</b>${t('enterprise.timeline_now_note')}</p><p><b>${t('enterprise.timeline_next')}</b>${t('enterprise.timeline_next_note')}</p></div>` : `<div class="enterprise-empty">${t('enterprise.no_people')}</div>`}</section>`; }
function shifts(el, staff) { const month = new Date().toISOString().slice(0, 7); const schedules = getSchedules({ month }); const rows = staff.map(p => { const mine = schedules.filter(x => x.personnelId === p.id); const hours = mine.reduce((sum, x) => sum + Number(x.duration || 8), 0); const nights = mine.filter(x => x.shift === 'night').length; const risk = hours > 190 || nights >= 8 ? 'danger' : hours > 170 || nights >= 5 ? 'warning' : 'good'; return { p, hours, nights, risk }; }); el.innerHTML = `<section class="card enterprise-panel"><div class="enterprise-heading"><div><p class="enterprise-kicker">${t('enterprise.shifts_eyebrow')}</p><h2>${t('enterprise.shifts_title')}</h2><p class="enterprise-help">${t('enterprise.shifts_note')}</p></div><span class="enterprise-badge">${t('enterprise.advisory')}</span></div><div class="table-scroll"><table class="enterprise-table"><thead><tr><th>${t('enterprise.person')}</th><th>${t('enterprise.hours')}</th><th>${t('enterprise.nights')}</th><th>${t('enterprise.rule')}</th><th>${t('enterprise.action')}</th></tr></thead><tbody>${rows.slice(0, 20).map(x => `<tr><td><strong>${esc(`${x.p.name} ${x.p.surname}`)}</strong><small>${esc(x.p.department || '')}</small></td><td>${x.hours}</td><td>${x.nights}</td><td><span class="status-${x.risk}">${t(`enterprise.risk_${x.risk}`)}</span></td><td><button class="btn-secondary text-xs" data-tab="workflow">${t('enterprise.request_review')}</button></td></tr>`).join('')}</tbody></table></div></section>`; }
function workflow(el, items) { el.innerHTML = `<section class="card enterprise-panel"><div class="enterprise-heading"><div><p class="enterprise-kicker">${t('enterprise.workflow_eyebrow')}</p><h2>${t('enterprise.workflow_title')}</h2><p class="enterprise-help">${t('enterprise.workflow_note')}</p></div></div>${canManage() ? `<div class="enterprise-inline-form"><input id="workflow-title" class="input-field" placeholder="${t('enterprise.workflow_placeholder')}"><button id="workflow-add" class="btn-primary">${t('enterprise.add_workflow')}</button></div>` : ''}<div class="enterprise-list">${items.map(x => `<article><div><strong>${esc(x.title)}</strong><small>${esc(x.owner)} · ${esc(x.createdAt)}</small><div class="progress"><i style="width:${Math.round(x.step / x.total * 100)}%"></i></div></div><span class="status-warning">${t('enterprise.step', { step: x.step, total: x.total })}</span></article>`).join('')}</div></section>`; }
function criticalResults(el, items) { el.innerHTML = `<section class="card enterprise-panel"><div class="enterprise-heading"><div><p class="enterprise-kicker">${t('enterprise.results_eyebrow')}</p><h2>${t('enterprise.results_title')}</h2><p class="enterprise-help">${t('enterprise.results_note')}</p></div><span class="enterprise-badge danger-badge">${items.filter(x => x.status !== 'resolved').length} ${t('enterprise.open_label')}</span></div><div class="enterprise-list">${items.map(x => `<article class="result-${esc(x.severity)}"><div><strong>${esc(x.test)} · ${esc(x.patient)}</strong><small>${esc(x.unit)} · ${t('enterprise.response_due')} ${esc(x.due)}</small></div><div class="enterprise-actions">${canManage() && x.status === 'open' ? `<button class="btn-secondary text-xs" data-result-action="ack" data-id="${esc(x.id)}">${t('enterprise.acknowledge')}</button>` : ''}${canManage() && x.status !== 'resolved' ? `<button class="btn-primary text-xs" data-result-action="resolve" data-id="${esc(x.id)}">${t('enterprise.resolve')}</button>` : x.status === 'resolved' ? `<span class="status-good">${t('enterprise.resolved')}</span>` : `<span class="status-info">${t('enterprise.read_only')}</span>`}</div></article>`).join('')}</div></section>`; }
function integrationView(el, items) { el.innerHTML = `<section class="card enterprise-panel"><div class="enterprise-heading"><div><p class="enterprise-kicker">${t('enterprise.integration_eyebrow')}</p><h2>${t('enterprise.integration_title')}</h2><p class="enterprise-help">${t('enterprise.integration_note')}</p></div></div><div class="resource-grid">${items.map(x => `<article><div><strong>${esc(x.resource)}</strong><small>${esc(x.standard)} · ${esc(x.direction)}</small></div><span class="status-${x.status === 'ready' ? 'good' : 'warning'}">${t(`enterprise.integration_${x.status}`)}</span><b>${x.errors} ${t('enterprise.errors')}</b>${canManage() ? `<button class="btn-secondary text-xs" data-integration-action="test" data-id="${esc(x.id)}">${t('enterprise.test_connection')}</button>` : `<span class="status-info">${t('enterprise.read_only')}</span>`}</article>`).join('')}</div></section>`; }
function auditView(el, logs) { el.innerHTML = `<div class="enterprise-section-grid"><section class="card enterprise-panel"><p class="enterprise-kicker">${t('enterprise.audit_eyebrow')}</p><h2>${t('enterprise.audit_title')}</h2><p class="enterprise-help">${t('enterprise.audit_note')}</p><div class="enterprise-audit-list">${logs.length ? logs.slice(0, 10).map(x => `<div><b>${esc(x.action)}</b><small>${esc(x.actor)} · ${new Date(x.at).toLocaleString('tr-TR')}</small><code>${esc(x.checksum || '')}</code></div>`).join('') : `<div class="enterprise-empty">${t('enterprise.no_audit')}</div>`}</div></section><section class="card enterprise-panel"><p class="enterprise-kicker">${t('enterprise.continuity_eyebrow')}</p><h2>${t('enterprise.continuity_title')}</h2><p class="enterprise-help">${t('enterprise.continuity_note')}</p><div class="enterprise-actions-stack"><button id="enterprise-migrate" class="btn-secondary">${t('enterprise.migrate')}</button><button id="enterprise-export" class="btn-primary">${t('enterprise.export_evidence')}</button></div><div class="enterprise-breakglass-form"><h3>${t('enterprise.breakglass_title')}</h3><select id="breakglass-resource" class="input-field"><option>Patient</option><option>DiagnosticReport</option><option>Personnel</option></select><textarea id="breakglass-reason" class="input-field" rows="3" placeholder="${t('enterprise.breakglass_placeholder')}"></textarea><button id="enterprise-breakglass" class="btn-secondary">${t('enterprise.open_access')}</button></div></section></div>`; }
