// ===== HASTA HAKLARI VE ŞİKAYET MERKEZİ =====
import { loadPatientRights, savePatientRights } from '../services/patient-rights-storage.js';
const t = (key, values) => window.miniappI18n?.t(key, values) ?? key;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
const categoryKeys = ['access', 'communication', 'care', 'rights', 'privacy', 'facility', 'billing', 'other'];
const priorityKeys = ['high', 'medium', 'low'];
const statusKeys = ['received', 'in-review', 'action', 'resolved', 'closed'];
const channelKeys = ['in-person', 'call', 'portal', 'written'];

export async function renderPatientRightsPage(el) {
  el.innerHTML = `<div class="card loading-pulse text-slate-400">${t('rights.loading')}</div>`;
  let complaints;
  try { complaints = await loadPatientRights(); } catch (error) { el.innerHTML = `<div class="card text-red-200">${t('rights.load_error')}</div>`; return; }
  let query = '', priority = 'all', status = 'all', notice = '', noticeError = false;
  const filtered = () => complaints.filter((item) => (priority === 'all' || item.priority === priority) && (status === 'all' || item.status === status) && (!query || [item.reference, item.department, item.summary, item.owner].join(' ').toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))));
  const commit = async (next, message) => { try { complaints = await savePatientRights(next); notice = message; noticeError = false; render(); } catch (error) { notice = t('rights.save_error'); noticeError = true; render(); } };
  const isOverdue = (item) => item.status !== 'closed' && item.status !== 'resolved' && item.dueDate && item.dueDate < new Date().toISOString().slice(0, 10);
  function render() {
    const open = complaints.filter((item) => !['resolved', 'closed'].includes(item.status)).length;
    const urgent = complaints.filter((item) => item.priority === 'high' && !['resolved', 'closed'].includes(item.status)).length;
    const overdue = complaints.filter(isOverdue).length;
    const actions = complaints.filter((item) => item.status === 'action').length;
    el.innerHTML = `<div class="rights-page fade-in"><section class="rights-hero"><div><p class="eyebrow">${t('rights.eyebrow')}</p><h1>${t('rights.title')}</h1><p>${t('rights.subtitle')}</p></div><div class="rights-live"><i></i><span>${t('rights.live')}</span></div></section><section class="rights-kpis"><div class="rights-kpi info"><span>${t('rights.kpis.total')}</span><strong>${complaints.length}</strong><small>${t('rights.kpis.total_note')}</small></div><div class="rights-kpi danger"><span>${t('rights.kpis.urgent')}</span><strong>${urgent}</strong><small>${t('rights.kpis.urgent_note')}</small></div><div class="rights-kpi warning"><span>${t('rights.kpis.overdue')}</span><strong>${overdue}</strong><small>${t('rights.kpis.overdue_note')}</small></div><div class="rights-kpi success"><span>${t('rights.kpis.actions')}</span><strong>${actions}</strong><small>${t('rights.kpis.actions_note')}</small></div></section><p class="rights-notice${noticeError ? ' error' : ''}" role="status">${esc(notice)}</p><section class="card rights-workspace"><div class="rights-toolbar"><div class="rights-filters"><input id="rights-search" class="input-field" value="${esc(query)}" placeholder="${t('rights.search')}" aria-label="${t('rights.search_label')}"><select id="rights-priority" class="input-field" aria-label="${t('rights.priority_label')}"><option value="all">${t('rights.filters.all_priorities')}</option>${priorityKeys.map((key) => `<option value="${key}" ${priority === key ? 'selected' : ''}>${t(`rights.priority.${key}`)}</option>`).join('')}</select><select id="rights-status" class="input-field" aria-label="${t('rights.status_label')}"><option value="all">${t('rights.filters.all_statuses')}</option>${statusKeys.map((key) => `<option value="${key}" ${status === key ? 'selected' : ''}>${t(`rights.status.${key}`)}</option>`).join('')}</select></div><button id="rights-add" class="btn-primary">${t('rights.actions.add')}</button></div><div class="rights-list">${filtered().length ? filtered().map(renderCard).join('') : `<div class="rights-empty"><strong>${t('rights.empty_title')}</strong><p>${t('rights.empty_note')}</p></div>`}</div></section></div>`;
    el.querySelector('#rights-search').addEventListener('input', (event) => { query = event.target.value; render(); const input = el.querySelector('#rights-search'); input.focus(); input.setSelectionRange(query.length, query.length); });
    el.querySelector('#rights-priority').addEventListener('change', (event) => { priority = event.target.value; render(); });
    el.querySelector('#rights-status').addEventListener('change', (event) => { status = event.target.value; render(); });
    el.querySelector('#rights-add').addEventListener('click', openDialog);
    el.querySelectorAll('[data-rights-action]').forEach((button) => button.addEventListener('click', () => handleAction(button.dataset.id, button.dataset.rightsAction)));
  }
  function renderCard(item) {
    return `<article class="rights-card ${item.priority === 'high' ? 'is-high' : ''} ${item.status === 'closed' ? 'is-closed' : ''}"><div class="rights-card-head"><div class="rights-reference"><strong>${esc(item.reference)}</strong><small>${esc(item.department)} · ${t(`rights.channel.${item.channel}`)}</small></div><div class="rights-badges"><span class="rights-badge ${item.priority}">${t(`rights.priority.${item.priority}`)}</span><span class="rights-badge ${item.status}">${t(`rights.status.${item.status}`)}</span>${isOverdue(item) ? `<span class="rights-badge high">${t('rights.overdue')}</span>` : ''}</div></div><p class="rights-summary">${esc(item.summary || t('rights.empty_value'))}</p><div class="rights-grid"><div><span>${t('rights.fields.category')}</span><strong>${t(`rights.category.${item.category}`)}</strong></div><div><span>${t('rights.fields.received')}</span><strong>${esc(item.received || t('rights.empty_value'))}</strong></div><div class="${isOverdue(item) ? 'overdue' : ''}"><span>${t('rights.fields.due')}</span><strong>${esc(item.dueDate || t('rights.empty_value'))}</strong></div><div><span>${t('rights.fields.owner')}</span><strong>${esc(item.owner || t('rights.unassigned'))}</strong></div></div><div class="rights-footer"><div class="rights-action">${t('rights.fields.action')}: <strong>${esc(item.action || t('rights.empty_value'))}</strong></div><div class="rights-actions">${item.status === 'received' ? `<button class="btn-primary" data-id="${esc(item.id)}" data-rights-action="review">${t('rights.actions.review')}</button>` : ''}${item.status === 'in-review' ? `<button class="btn-secondary" data-id="${esc(item.id)}" data-rights-action="action">${t('rights.actions.open_action')}</button>` : ''}${item.status === 'action' ? `<button class="btn-secondary" data-id="${esc(item.id)}" data-rights-action="resolve">${t('rights.actions.resolve')}</button>` : ''}${item.status === 'resolved' ? `<button class="btn-secondary" data-id="${esc(item.id)}" data-rights-action="close">${t('rights.actions.close')}</button>` : ''}<button class="btn-secondary" data-id="${esc(item.id)}" data-rights-action="delete">${t('rights.actions.delete')}</button></div></div></article>`;
  }
  async function handleAction(id, action) {
    const index = complaints.findIndex((item) => item.id === id); if (index < 0) return;
    if (action === 'delete' && !window.confirm(t('rights.confirm_delete'))) return;
    const next = complaints.map((item) => ({ ...item }));
    if (action === 'delete') next.splice(index, 1);
    else if (action === 'review') next[index].status = 'in-review';
    else if (action === 'action') next[index].status = 'action';
    else if (action === 'resolve') next[index].status = 'resolved';
    else if (action === 'close') next[index].status = 'closed';
    await commit(next, t(`rights.notices.${action}`));
  }
  function openDialog() {
    const dialog = document.createElement('dialog'); dialog.className = 'rights-dialog';
    dialog.innerHTML = `<form method="dialog"><p class="eyebrow">${t('rights.form.eyebrow')}</p><h2>${t('rights.form.title')}</h2><p class="note">${t('rights.form.note')}</p><div class="rights-form-grid"><label class="rights-field"><span>${t('rights.form.reference')}</span><input id="rights-reference" class="input-field" placeholder="${t('rights.form.reference_placeholder')}"></label><label class="rights-field"><span>${t('rights.form.received')}</span><input id="rights-received" class="input-field" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label class="rights-field"><span>${t('rights.form.department')}</span><input id="rights-department" class="input-field" required></label><label class="rights-field"><span>${t('rights.form.due')}</span><input id="rights-due" class="input-field" type="date" required></label><label class="rights-field"><span>${t('rights.form.category')}</span><select id="rights-category" class="input-field">${categoryKeys.map((key) => `<option value="${key}">${t(`rights.category.${key}`)}</option>`).join('')}</select></label><label class="rights-field"><span>${t('rights.form.priority')}</span><select id="rights-new-priority" class="input-field">${priorityKeys.map((key) => `<option value="${key}">${t(`rights.priority.${key}`)}</option>`).join('')}</select></label><label class="rights-field"><span>${t('rights.form.channel')}</span><select id="rights-channel" class="input-field">${channelKeys.map((key) => `<option value="${key}">${t(`rights.channel.${key}`)}</option>`).join('')}</select></label><label class="rights-field"><span>${t('rights.form.owner')}</span><input id="rights-owner" class="input-field"></label><label class="rights-field wide"><span>${t('rights.form.summary')}</span><textarea id="rights-summary" class="input-field" rows="3" required></textarea></label><label class="rights-field wide"><span>${t('rights.form.action')}</span><textarea id="rights-action" class="input-field" rows="2"></textarea></label></div><div class="rights-dialog-actions"><button type="button" id="rights-cancel" class="btn-secondary">${t('rights.form.cancel')}</button><button class="btn-primary">${t('rights.form.save')}</button></div></form>`;
    document.body.append(dialog); dialog.showModal(); dialog.querySelector('#rights-cancel').onclick = () => dialog.close(); dialog.addEventListener('close', () => dialog.remove(), { once: true });
    dialog.querySelector('#rights-due').value = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);
    dialog.querySelector('form').addEventListener('submit', async (event) => { event.preventDefault(); const value = (id) => dialog.querySelector(id).value.trim(); const item = { id:`pr-${Date.now()}`, reference:value('#rights-reference') || t('rights.anonymous'), received:value('#rights-received'), department:value('#rights-department'), dueDate:value('#rights-due'), category:dialog.querySelector('#rights-category').value, priority:dialog.querySelector('#rights-new-priority').value, channel:dialog.querySelector('#rights-channel').value, owner:value('#rights-owner'), summary:value('#rights-summary'), action:value('#rights-action'), status:'received' }; if (!item.department || !item.summary) return; await commit([...complaints, item], t('rights.notices.created')); dialog.close(); });
  }
  render();
}
