// ===== MERKEZİ PERSONEL KAYDI =====
import { getPersonnel, updatePersonnel } from '../state.js';
import { readPlatform, writePlatform, uid, today, dateLabel, esc } from '../services/platform-storage.js';
import { showToast } from '../notifications.js';
const t=(key,values)=>window.miniappI18n?.t(key,values)??key;

export async function renderPersonnel360Page(container){
  const staff=getPersonnel({status:'active'}); const meta=await readPlatform('people_meta',{}); const selected=staff.find(p=>String(p.id)===String(meta.selected))||staff[0];
  container.innerHTML=`<div class="fade-in space-y-5"><header><p class="text-xs uppercase tracking-widest text-cyan-300">${t('platform.people')}</p><h1 class="text-2xl font-bold text-white">${t('platform.profile')}</h1><p class="text-slate-400 text-sm mt-1">${t('platform.profile_subtitle')}</p></header><div class="card"><div class="grid md:grid-cols-[1fr_2fr] gap-4 items-end"><div><label class="label">${t('platform.select_person')}</label><select id="people-select" class="input-field w-full">${staff.map(p=>`<option value="${p.id}" ${p.id===selected?.id?'selected':''}>${esc(`${p.name||''} ${p.surname||''}`)}</option>`).join('')}</select></div><span class="text-xs text-slate-500">${t('platform.single_source')}</span></div></div><div id="people-panel"></div></div>`;
  const panel=container.querySelector('#people-panel');
  if(!selected){panel.innerHTML=`<div class="empty-state card"><div class="title">${t('platform.no_records')}</div></div>`;return;}
  const m=meta[selected.id]||{}; const gaps=[!selected.department,!selected.title,!selected.phone,!m.manager,!m.skills].filter(Boolean).length;
  panel.innerHTML=`<div class="grid lg:grid-cols-[1.15fr_.85fr] gap-5"><section class="card"><div class="flex items-start justify-between gap-3 mb-5"><div><span class="badge">${esc(selected.status||t('platform.active'))}</span><h2 class="text-xl font-semibold text-white mt-2">${esc(`${selected.name||''} ${selected.surname||''}`)}</h2><p class="text-slate-400">${esc(selected.title||t('platform.not_defined'))} · ${esc(selected.department||t('platform.not_defined'))}</p></div><span class="text-3xl">👤</span></div><div class="grid md:grid-cols-2 gap-4"><div><label class="label">${t('platform.department')}</label><input id="p-department" class="input-field w-full" value="${esc(selected.department||'')}"></div><div><label class="label">${t('platform.title')}</label><input id="p-title" class="input-field w-full" value="${esc(selected.title||'')}"></div><div><label class="label">${t('platform.phone')}</label><input id="p-phone" class="input-field w-full" value="${esc(selected.phone||'')}"></div><div><label class="label">${t('platform.manager')}</label><input id="p-manager" class="input-field w-full" value="${esc(m.manager||'')}"></div></div><button id="people-update" class="btn-primary mt-5">${t('platform.save')}</button></section><section class="space-y-5"><div class="card"><h2 class="text-lg font-semibold text-white mb-4">${t('platform.data_quality')}</h2><div class="text-3xl font-bold ${gaps?'text-amber-300':'text-emerald-300'}">${Math.round((1-gaps/5)*100)}%</div><p class="text-sm text-slate-400 mt-2">${gaps?t('platform.profile_missing',{count:gaps}):t('platform.profile_complete')}</p></div><div class="card"><h2 class="text-lg font-semibold text-white mb-3">${t('platform.timeline')}</h2><p class="text-sm text-slate-300">${t('platform.profile_source')}</p><p class="text-xs text-slate-500 mt-2">${t('platform.last_update')} · ${dateLabel(m.updatedAt||today())}</p></div></section></div>`;
  container.querySelector('#people-select').onchange=async e=>{meta.selected=e.target.value;await writePlatform('people_meta',meta);renderPersonnel360Page(container);};
  container.querySelector('#people-update').onclick=async()=>{const dept=container.querySelector('#p-department').value.trim(),title=container.querySelector('#p-title').value.trim(),phone=container.querySelector('#p-phone').value.trim(),manager=container.querySelector('#p-manager').value.trim();updatePersonnel(selected.id,{department:dept,title,phone});meta[selected.id]={...m,manager,updatedAt:today()};await writePlatform('people_meta',meta);await appendChange('platform.change_profile');showToast(t('platform.saved'),'success');renderPersonnel360Page(container);};
}
async function appendChange(actionKey){const changes=await readPlatform('changes',[]);changes.unshift({id:uid('change'),actionKey,whoKey:'platform.current_user',at:today()});await writePlatform('changes',changes.slice(0,50));}
