// ===== YÖNETİCİ ÖZETİ VE AKILLI YARDIM =====
import { getPersonnel } from '../state.js';
import { readPlatform, writePlatform, today, esc } from '../services/platform-storage.js';
import { showToast } from '../notifications.js';
const MODEL_ID='dc2db118-7888-466a-a8d1-bf9d96bab4b6';
const t=(key,values)=>window.miniappI18n?.t(key,values)??key;
export async function renderPlatformAIPage(container){
 const staff=getPersonnel({status:'active'}); const [tasks,tickets,scenarios]=await Promise.all([readPlatform('daily_tasks',[]),readPlatform('tickets',[]),readPlatform('scenarios',[])]);
 container.innerHTML=`<div class="fade-in space-y-5"><header><p class="text-xs uppercase tracking-widest text-cyan-300">${t('platform.ai_summary')}</p><h1 class="text-2xl font-bold text-white">${t('platform.ai_title')}</h1><p class="text-slate-400 text-sm mt-1">${t('platform.ai_subtitle')}</p></header><div class="grid md:grid-cols-3 gap-4">${kpi(t('platform.active_staff'),staff.length)}${kpi(t('platform.open_tasks'),tasks.filter(x=>!x.done).length)}${kpi(t('platform.open_tickets'),tickets.filter(x=>x.status==='open').length)}</div><section class="card"><div class="flex flex-wrap justify-between items-center gap-3"><div><h2 class="text-lg font-semibold text-white">${t('platform.ai_summary')}</h2><p class="text-sm text-slate-400 mt-1">${t('platform.ai_disclaimer')}</p></div><button id="ai-generate" class="btn-primary">${t('platform.generate_summary')}</button></div><div id="ai-result" class="mt-5 rounded-xl border border-white/5 bg-white/[.03] p-4 min-h-28 text-sm leading-7 text-slate-300">${t('platform.ai_empty')}</div></section><section class="card"><h2 class="text-lg font-semibold text-white mb-3">${t('platform.forecast')}</h2><p class="text-sm text-slate-400">${t('platform.forecast_desc',{count:scenarios.length})}</p></section></div>`;
 container.querySelector('#ai-generate').onclick=async()=>{const out=container.querySelector('#ai-result');const btn=container.querySelector('#ai-generate');btn.disabled=true;out.textContent=t('platform.summary_loading');try{const result=await window.miniappsAI.callModel({modelId:MODEL_ID,messages:[{role:'system',content:t('platform.ai_system')},{role:'user',content:JSON.stringify({staff:staff.length,openTasks:tasks.filter(x=>!x.done).length,openTickets:tickets.filter(x=>x.status==='open').length,scenarios:scenarios.length,date:today()})}],timeoutMs:30000,outputMediaPersistence:'temporary'});const text=window.miniappsAI.extractText(result);out.textContent=text||t('platform.ai_empty');await writePlatform('last_summary',{text,at:today()});}catch{out.textContent=t('platform.summary_error');showToast(t('platform.summary_error'),'error');}finally{btn.disabled=false;}};
}
function kpi(label,value){return `<div class="card"><p class="text-xs text-slate-400">${label}</p><p class="text-2xl font-bold text-white mt-2">${esc(value)}</p></div>`;}
