// ===== GELİR DÖNGÜSÜ VE SGK TAKİP =====
import { readPlatform, writePlatform, uid, today, esc } from '../services/platform-storage.js';
import { showToast } from '../notifications.js';

const t = (key, values) => window.miniappI18n?.t(key, values) ?? key;
const KEY = 'revenue_cycle_claims';
const SEED = [
  { id: 'claim_1', patient: 'Mehmet Yılmaz', payer: 'SGK', service: 'Acil yatış paketi', amount: 18400, status: 'submitted', risk: 'low', date: '2026-01-11' },
  { id: 'claim_2', patient: 'Fatma Çelik', payer: 'SGK', service: 'Dahiliye takip paketi', amount: 9600, status: 'review', risk: 'watch', date: '2026-01-10' },
  { id: 'claim_3', patient: 'Ahmet Kaya', payer: 'Özel sigorta', service: 'Yoğun bakım hizmeti', amount: 32600, status: 'denied', risk: 'high', date: '2026-01-08' },
  { id: 'claim_4', patient: 'Zeliha Demir', payer: 'SGK', service: 'Doğum hizmeti', amount: 14200, status: 'paid', risk: 'low', date: '2026-01-07' },
];

export async function renderRevenueCyclePage(container) {
  container.innerHTML = `<div class="card loading-pulse text-slate-400">${t('revenue.loading')}</div>`;
  const stored = await readPlatform(KEY, SEED); let claims = Array.isArray(stored) ? stored : SEED.map(item => ({ ...item })); let filter = 'all';
  const persist = async () => { try { await writePlatform(KEY, claims); } catch { showToast(t('revenue.save_error'), 'error'); } };
  const render = () => {
    const total = claims.reduce((sum, item) => sum + Number(item.amount || 0), 0); const pending = claims.filter(item => item.status !== 'paid').reduce((sum, item) => sum + Number(item.amount || 0), 0); const denied = claims.filter(item => item.status === 'denied').length; const visible = filter === 'all' ? claims : claims.filter(item => item.status === filter);
    container.innerHTML = `<div class="fade-in space-y-5 revenue-page"><header class="flex flex-wrap items-start justify-between gap-4"><div><p class="section-kicker">${t('revenue.eyebrow')}</p><h1 class="text-2xl font-bold text-white">${t('revenue.title')}</h1><p class="text-slate-400 text-sm mt-1 max-w-3xl">${t('revenue.subtitle')}</p></div><button id="revenue-new" class="btn-primary">${t('revenue.new_claim')}</button></header><section class="grid grid-cols-2 lg:grid-cols-4 gap-3"><div class="card market-stat"><span class="market-stat-label">${t('revenue.total_value')}</span><strong>₺${total.toLocaleString('tr-TR')}</strong><span>${claims.length} ${t('revenue.claims')}</span></div><div class="card market-stat"><span class="market-stat-label">${t('revenue.pending_value')}</span><strong class="text-amber-300">₺${pending.toLocaleString('tr-TR')}</strong><span>${t('revenue.pending_note')}</span></div><div class="card market-stat"><span class="market-stat-label">${t('revenue.denials')}</span><strong class="text-red-300">${denied}</strong><span>${t('revenue.denials_note')}</span></div><div class="card market-stat"><span class="market-stat-label">${t('revenue.collection_rate')}</span><strong class="text-emerald-300">${total ? Math.round((total - pending) / total * 100) : 0}%</strong><span>${t('revenue.collection_note')}</span></div></section><section class="card"><div class="flex flex-wrap gap-2 mb-4" role="tablist" aria-label="${t('revenue.filter_label')}">${['all','submitted','review','denied','paid'].map(key => `<button class="market-filter ${filter === key ? 'active' : ''}" data-filter="${key}" role="tab" aria-selected="${filter === key}">${t(`revenue.filter_${key}`)} <span>${key === 'all' ? claims.length : claims.filter(item => item.status === key).length}</span></button>`).join('')}</div><div class="space-y-2">${visible.length ? visible.map(claimCard).join('') : `<div class="empty-state"><div class="icon">+</div><div class="title">${t('revenue.empty_title')}</div><p>${t('revenue.empty_desc')}</p></div>`}</div></section><p class="text-xs text-slate-500">${t('revenue.compliance_note')}</p></div>`;
    container.querySelectorAll('[data-filter]').forEach(button => button.onclick = () => { filter = button.dataset.filter; render(); }); container.querySelectorAll('[data-paid]').forEach(button => button.onclick = async () => { const claim = claims.find(item => item.id === button.dataset.paid); if (!claim) return; claim.status = 'paid'; await persist(); showToast(t('revenue.paid'), 'success'); render(); }); container.querySelector('#revenue-new').onclick = openModal;
  };
  const openModal = () => { const modal = document.createElement('div'); modal.className = 'fixed inset-0 z-[70] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4'; modal.innerHTML = `<form class="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl fade-in"><h2 class="text-xl font-bold text-white">${t('revenue.modal_title')}</h2><div class="space-y-3 mt-5"><label class="label">${t('revenue.patient')}<input name="patient" class="input-field w-full mt-1" required></label><label class="label">${t('revenue.service')}<input name="service" class="input-field w-full mt-1" required></label><label class="label">${t('revenue.payer')}<select name="payer" class="input-field w-full mt-1"><option>SGK</option><option>${t('revenue.private_payer')}</option><option>${t('revenue.self_pay')}</option></select></label><label class="label">${t('revenue.amount')}<input name="amount" type="number" min="0" class="input-field w-full mt-1" required></label></div><div class="flex gap-3 mt-5"><button class="btn-primary flex-1" type="submit">${t('revenue.save')}</button><button class="btn-secondary flex-1" type="button">${t('revenue.cancel')}</button></div></form>`; document.body.appendChild(modal); modal.querySelector('button[type="button"]').onclick = () => modal.remove(); modal.querySelector('form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); claims.unshift({ id: uid('claim'), patient: String(form.get('patient')).trim(), service: String(form.get('service')).trim(), payer: String(form.get('payer')), amount: Number(form.get('amount')) || 0, status: 'review', risk: 'watch', date: today() }); await persist(); modal.remove(); showToast(t('revenue.created'), 'success'); render(); }; };
  render();
}
function claimCard(claim) { const action = claim.status === 'paid' ? `<span class="text-xs text-emerald-300">${t('revenue.paid')}</span>` : `<button class="btn-secondary text-xs" data-paid="${esc(claim.id)}">${t('revenue.mark_paid')}</button>`; return `<article class="card flex flex-wrap items-center gap-4"><div class="flex-1 min-w-[12rem]"><p class="text-sm font-semibold text-white">${esc(claim.patient)}</p><p class="text-xs text-slate-400 mt-1">${esc(claim.service)} · ${esc(claim.payer)} · ${esc(claim.date)}</p></div><div><p class="text-sm font-semibold text-white">₺${Number(claim.amount || 0).toLocaleString('tr-TR')}</p><p class="text-xs ${claim.risk === 'high' ? 'text-red-300' : claim.risk === 'watch' ? 'text-amber-300' : 'text-emerald-300'}">${t(`revenue.risk_${claim.risk}`)}</p></div><span class="market-status status-${claim.status === 'paid' ? 'ready' : claim.status === 'denied' ? 'missing' : 'partial'}">${t(`revenue.status_${claim.status}`)}</span>${action}</article>`; }
