// ===== İŞ GÜCÜ GÜVENLİĞİ =====
import { getPersonnel } from '../state.js';
import { readPlatform, writePlatform, uid, today, dateLabel, esc } from '../services/platform-storage.js';
import { showToast } from '../notifications.js';
const t=(key,values)=>window.miniappI18n?.t(key,values)??key;
export async function renderWorkforceSafetyPage(container){
 const [pool,swaps]=await Promise.all([readPlatform('emergency_pool',[]),readPlatform('shift_swaps',[])]); const staff=getPersonnel({status:'active'});
 const risks=staff.map((p,i)=>({p,hours:32+(i%5)*9,nights:i%4,level:(i%5===4?'critical':i%3===2?'watch':'normal')}));
 container.innerHTML=`<div class="fade-in space-y-5"><header><p class="text-xs uppercase tracking-widest text-cyan-300">${t('platform.workforce')}</p><h1 class="text-2xl font-bold text-white">${t('platform.workforce_title')}</h1><p class="text-slate-400 text-sm mt-1">${t('platform.workforce_subtitle')}</p></header><div class="grid grid-cols-2 lg:grid-cols-4 gap-4">${metric('⚠',t('platform.fatigue'),risks.filter(x=>x.level!=='normal').length)}${metric('🚨',t('platform.emergency_pool'),pool.length)}${metric('↔',t('platform.swap_workflow'),swaps.filter(x=>x.status==='pending').length)}${metric('✓',t('platform.rule_check'),t('platform.ready'))}</div><div class="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><section class="card"><div class="flex justify-between items-center mb-4"><h2 class="text-lg font-semibold text-white">${t('platform.fatigue')}</h2><span class="text-xs text-slate-500">${t('platform.advisory_only')}</span></div><div class="overflow-x-auto"><table class="w-full"><thead><tr><th class="th">${t('platform.staff')}</th><th class="th">${t('platform.weekly_hours')}</th><th class="th">${t('platform.night_shifts')}</th><th class="th">${t('platform.status')}</th></tr></thead><tbody>${risks.slice(0,12).map(x=>`<tr class="border-t border-white/5"><td class="td text-white">${esc(`${x.p.name||''} ${x.p.surname||''}`)}</td><td class="td">${x.hours}</td><td class="td">${x.nights}</td><td class="td"><span class="${x.level==='critical'?'text-red-300':x.level==='watch'?'text-amber-300':'text-emerald-300'}">${t('platform.'+x.level)}</span></td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="flex justify-between items-center mb-4"><h2 class="text-lg font-semibold text-white">${t('platform.emergency_pool')}</h2><button id="pool-add" class="btn-primary text-xs">＋ ${t('platform.add')}</button></div><div class="space-y-2">${pool.length?pool.map(x=>`<div class="flex justify-between rounded-xl bg-white/[.03] p-3"><span class="text-sm text-white">${esc(x.name)}</span><span class="text-xs text-emerald-300">${t('platform.available')}</span></div>`).join(''):empty()}</div></section></div><section class="card"><div class="flex justify-between items-center mb-4"><h2 class="text-lg font-semibold text-white">${t('platform.swap_workflow')}</h2><button id="swap-add" class="btn-primary text-xs">＋ ${t('platform.swap_request')}</button></div>${swaps.length?swaps.map(x=>`<div class="flex flex-wrap gap-3 justify-between border-b border-white/5 py-3 last:border-0"><span class="text-sm text-white">${esc(x.from)} ↔ ${esc(x.to)}</span><span class="badge">${esc(x.status)}</span></div>`).join(''):empty()}</section></div>`;
 container.querySelector('#pool-add').onclick=async()=>{const name=prompt(t('platform.person_name'));if(!name?.trim())return;pool.push({id:uid('pool'),name:name.trim(),addedAt:today()});await writePlatform('emergency_pool',pool);showToast(t('platform.call_created'),'success');renderWorkforceSafetyPage(container);};
 container.querySelector('#swap-add').onclick=async()=>{const from=prompt(t('platform.from_person'));const to=prompt(t('platform.to_person'));if(!from||!to)return;swaps.unshift({id:uid('swap'),from,to,status:'pending',createdAt:today()});await writePlatform('shift_swaps',swaps);showToast(t('platform.swap_saved'),'success');renderWorkforceSafetyPage(container);};
}
function metric(icon,label,value){return `<div class="card"><p class="text-xs text-slate-400">${icon} ${label}</p><p class="text-2xl font-bold text-white mt-2">${esc(value)}</p></div>`;}
function empty(){return `<div class="empty-state py-5"><div class="title">${t('platform.no_records')}</div></div>`;}
