// ===== KURUMSAL RİSK VE GÜVENLİK VERİ SERVİSİ =====
import { readPlatform, writePlatform, uid, today } from './platform-storage.js';
import { appendEnterpriseAudit } from './enterprise-storage.js';

const KEY = 'enterprise_risk_center';
const now = () => new Date().toISOString();
const seed = () => ({
  records: [
    { id: 'erc-sec-1', stage: 'security', severity: 'critical', titleKey: 'enterprise_risk.sample.mfa', owner: 'Bilgi Güvenliği', due: '2026-09-18', status: 'open', noteKey: 'enterprise_risk.sample.mfa_note' },
    { id: 'erc-sec-2', stage: 'security', severity: 'high', titleKey: 'enterprise_risk.sample.export', owner: 'SOC', due: '2026-09-25', status: 'in_progress', noteKey: 'enterprise_risk.sample.export_note' },
    { id: 'erc-capa-1', stage: 'capa', severity: 'high', titleKey: 'enterprise_risk.sample.capa', owner: 'Kalite Direktörlüğü', due: '2026-09-12', status: 'in_progress', noteKey: 'enterprise_risk.sample.capa_note' },
    { id: 'erc-inc-1', stage: 'incidents', severity: 'critical', titleKey: 'enterprise_risk.sample.incident', owner: 'Hasta Güvenliği', due: '2026-09-10', status: 'open', noteKey: 'enterprise_risk.sample.incident_note' },
    { id: 'erc-comp-1', stage: 'competency', severity: 'high', titleKey: 'enterprise_risk.sample.license', owner: 'İK ve Eğitim', due: '2026-09-30', status: 'open', noteKey: 'enterprise_risk.sample.license_note' },
    { id: 'erc-bcp-1', stage: 'continuity', severity: 'medium', titleKey: 'enterprise_risk.sample.dependency', owner: 'Operasyon', due: '2026-10-05', status: 'in_progress', noteKey: 'enterprise_risk.sample.dependency_note' },
    { id: 'erc-kpi-1', stage: 'kpi', severity: 'medium', titleKey: 'enterprise_risk.sample.kpi', owner: 'Kalite Yönetimi', due: '2026-09-20', status: 'resolved', noteKey: 'enterprise_risk.sample.kpi_note' },
  ], updatedAt: now(), schema: 'enterprise-risk-v1'
});
const normalize = value => { const base = seed(); const records = Array.isArray(value?.records) ? value.records : base.records; return { ...base, ...(value || {}), records: records.map(item => ({ ...item, id: String(item.id || uid('risk')), stage: ['security','capa','incidents','competency','continuity','kpi'].includes(item.stage) ? item.stage : 'security', severity: ['critical','high','medium'].includes(item.severity) ? item.severity : 'medium', status: ['open','in_progress','resolved'].includes(item.status) ? item.status : 'open', due: item.due || today(), owner: String(item.owner || 'Atanmadı'), titleKey: item.titleKey || 'enterprise_risk.untitled', noteKey: item.noteKey || 'enterprise_risk.empty_note' })) }; };
export async function loadEnterpriseRisk() { return normalize(await readPlatform(KEY, seed())); }
export async function updateRiskRecord(id, status, actor = 'system') { const state = await loadEnterpriseRisk(); const record = state.records.find(item => item.id === id); if (!record) throw new Error('risk_record_not_found'); const before = record.status; record.status = ['open','in_progress','resolved'].includes(status) ? status : before; state.updatedAt = now(); await writePlatform(KEY, state); await appendEnterpriseAudit({ action: 'enterprise_risk_record_updated', actor, resource: id, before: { status: before }, after: { status: record.status, stage: record.stage } }); return state; }
export async function addRiskRecord(input, actor = 'system') { const state = await loadEnterpriseRisk(); const record = { id: uid('risk'), stage: input.stage, severity: input.severity, titleKey: 'enterprise_risk.custom_title', title: input.title, owner: input.owner, due: input.due, status: 'open', noteKey: 'enterprise_risk.custom_note', note: input.note }; state.records.unshift(record); state.updatedAt = now(); await writePlatform(KEY, state); await appendEnterpriseAudit({ action: 'enterprise_risk_record_created', actor, resource: record.id, after: { stage: record.stage, severity: record.severity, owner: record.owner } }); return state; }
export async function exportEnterpriseRisk(state, actor = 'system') { const payload = { schema: 'hospital-pys-enterprise-risk-v1', exportedAt: now(), actor, ...state }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `hastane-pys-kurumsal-risk-${today()}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); await appendEnterpriseAudit({ action: 'enterprise_risk_evidence_exported', actor, resource: 'enterprise-risk-center', after: { records: state.records.length } }); }
export function riskSummary(state) { const records = state.records || []; return { total: records.length, open: records.filter(item => item.status !== 'resolved').length, critical: records.filter(item => item.severity === 'critical' && item.status !== 'resolved').length, overdue: records.filter(item => item.status !== 'resolved' && item.due < today()).length, completed: records.filter(item => item.status === 'resolved').length }; }
